In [2]:
import laspy
import pandas as pd
import os
from IPython.display import display, HTML

In [ ]:
# Pfad zur Punktwolke (anpassbar)
# pc_path = r"C:\_Data\BTh11\BTh11_Trieblaengenwachstum\05_Software_Comparison\50_BaseData\PointCloud\20250326\20250326_DJIMini3Pro_Kirsche_Metashape_clipped.las"
# pc_path = r"C:\_Data\BTh11\BTh11_Trieblaengenwachstum\05_Software_Comparison\50_BaseData\PointCloud\20250326\20250326_DJIMini3Pro_Kirsche_Drone2Map_clipped.las"
# pc_path = r"C:\_Data\BTh11\BTh11_Trieblaengenwachstum\05_Software_Comparison\50_BaseData\PointCloud\20250311\20250311_DJIMini3Pro_Kirsche_Metashape_clipped.las"
# pc_path = r"C:\_Data\BTh11\BTh11_Trieblaengenwachstum\05_Software_Comparison\50_BaseData\PointCloud\20250311\20250311_DJIMini3Pro_Kirsche_Drone2Map_clipped.las"
# pc_path = r"F:\20250319_DJIMini3Pro_Kirsche_Metashape.las"
# pc_path = r"C:\_Data\BTh11\BTh11_Trieblaengenwachstum\07_Check_PG-PointCloud_Completeness\70_BaseDate\PointCloud\20250319_RTC360_Kirsche_clipped.las"
pc_path = r"C:\_Data\BTh11\BTh11_Trieblaengenwachstum\07_Check_PG-PointCloud_Completeness\70_BaseDate\PointCloud\20250319_DJIMini3Pro_Kirsche_Metashape_clipped.las"


# LAS-Datei einlesen und verf√ºgbare Punktattribute anzeigen
try:
    las = laspy.read(pc_path)
    dims = list(las.point_format.dimension_names)
    print(f"Datei: {os.path.basename(pc_path)}")
    print(f"Anzahl Punkte: {len(las.points)}")
    print(f"Verf√ºgbare Punktattribute: {dims}")
except Exception as e:
    print(f"Fehler beim Lesen der Datei: {e}")

# Ersten 20 Werte aller Punktattribute in einem DataFrame speichern
try:
    data = {}
    for dim in dims:
        try:
            values = getattr(las, dim)
            data[dim] = values[:20]
        except AttributeError:
            print(f"Attribut {dim} konnte nicht geladen werden.")
    
    df = pd.DataFrame(data)

    # DataFrame als HTML-Tabelle anzeigen
    display(HTML(df.to_html(max_cols=200, notebook=True)))
except Exception as e:
    print(f"Fehler beim Erstellen der Tabelle: {e}")

Datei: 20250319_RTC360_Kirsche_clipped.las
Anzahl Punkte: 212935030
Verf√ºgbare Punktattribute: ['X', 'Y', 'Z', 'intensity', 'return_number', 'number_of_returns', 'scan_direction_flag', 'edge_of_flight_line', 'classification', 'synthetic', 'key_point', 'withheld', 'scan_angle_rank', 'user_data', 'point_source_id', 'red', 'green', 'blue']